export const characterLevelUp = [
	{
		level: 1,
		materials: [
			{ mora: 0 },
			{ expBooks: 0 },
			{ localSpeciality: 0 },
			{ commonMaterial1: 0 },
			{ commonMaterial2: 0 },
			{ commonMaterial3: 0 },
			{ sliver: 0 },
			{ fragments: 0 },
			{ chunks: 0 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 0 },
		],
	},
	{
		level: 20,
		materials: [
			{ mora: 19495 },
			{ expBooks: 5 },
			{ localSpeciality: 0 },
			{ commonMaterial1: 0 },
			{ commonMaterial2: 0 },
			{ commonMaterial3: 0 },
			{ sliver: 0 },
			{ fragments: 0 },
			{ chunks: 0 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 0 },
		],
	},
	{
		level: 21,
		materials: [
			{ mora: 42470 },
			{ expBooks: 6 },
			{ localSpeciality: 3 },
			{ commonMaterial1: 3 },
			{ commonMaterial2: 0 },
			{ commonMaterial3: 0 },
			{ sliver: 1 },
			{ fragments: 0 },
			{ chunks: 0 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 0 },
		],
	},
	{
		level: 40,
		materials: [
			{ mora: 155930 },
			{ expBooks: 34 },
			{ localSpeciality: 3 },
			{ commonMaterial1: 3 },
			{ commonMaterial2: 0 },
			{ commonMaterial3: 0 },
			{ sliver: 1 },
			{ fragments: 0 },
			{ chunks: 0 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 0 },
		],
	},
	{
		level: 41,
		materials: [
			{ mora: 205190 },
			{ expBooks: 37 },
			{ localSpeciality: 13 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 0 },
			{ commonMaterial3: 0 },
			{ sliver: 1 },
			{ fragments: 3 },
			{ chunks: 0 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 2 },
		],
	},
	{
		level: 50,
		materials: [
			{ mora: 312275 },
			{ expBooks: 64 },
			{ localSpeciality: 13 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 0 },
			{ commonMaterial3: 0 },
			{ sliver: 1 },
			{ fragments: 3 },
			{ chunks: 0 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 2 },
		],
	},
	{
		level: 51,
		materials: [
			{ mora: 386370 },
			{ expBooks: 67 },
			{ localSpeciality: 33 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 12 },
			{ commonMaterial3: 0 },
			{ sliver: 1 },
			{ fragments: 9 },
			{ chunks: 0 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 6 },
		],
	},
	{
		level: 60,
		materials: [
			{ mora: 543730 },
			{ expBooks: 106 },
			{ localSpeciality: 33 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 12 },
			{ commonMaterial3: 0 },
			{ sliver: 1 },
			{ fragments: 9 },
			{ chunks: 0 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 6 },
		],
	},
	{
		level: 61,
		materials: [
			{ mora: 643905 },
			{ expBooks: 111 },
			{ localSpeciality: 63 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 30 },
			{ commonMaterial3: 0 },
			{ sliver: 1 },
			{ fragments: 9 },
			{ chunks: 3 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 14 },
		],
	},
	{
		level: 70,
		materials: [
			{ mora: 863660 },
			{ expBooks: 166 },
			{ localSpeciality: 63 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 30 },
			{ commonMaterial3: 0 },
			{ sliver: 1 },
			{ fragments: 9 },
			{ chunks: 3 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 14 },
		],
	},
	{
		level: 71,
		materials: [
			{ mora: 991295 },
			{ expBooks: 173 },
			{ localSpeciality: 108 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 30 },
			{ commonMaterial3: 12 },
			{ sliver: 1 },
			{ fragments: 9 },
			{ chunks: 9 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 26 },
		],
	},
	{
		level: 80,
		materials: [
			{ mora: 1286905 },
			{ expBooks: 247 },
			{ localSpeciality: 108 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 30 },
			{ commonMaterial3: 12 },
			{ sliver: 1 },
			{ fragments: 9 },
			{ chunks: 9 },
			{ gemstones: 0 },
			{ bossAscensionMaterial: 26 },
		],
	},
	{
		level: 81,
		materials: [
			{ mora: 1443540 },
			{ expBooks: 256 },
			{ localSpeciality: 168 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 30 },
			{ commonMaterial3: 36 },
			{ sliver: 1 },
			{ fragments: 9 },
			{ chunks: 9 },
			{ gemstones: 6 },
			{ bossAscensionMaterial: 46 },
		],
	},
	{
		level: 90,
		materials: [
			{ mora: 2092530 },
			{ expBooks: 419 },
			{ localSpeciality: 168 },
			{ commonMaterial1: 18 },
			{ commonMaterial2: 30 },
			{ commonMaterial3: 36 },
			{ sliver: 1 },
			{ fragments: 9 },
			{ chunks: 9 },
			{ gemstones: 6 },
			{ bossAscensionMaterial: 46 },
		],
	},
];

export const talentLevelUp = [
	{
		level: 1,
		materials: {
			mora: 0,
			bronzeTalentBooks: 0,
			silverTalentBooks: 0,
			goldTalentBooks: 0,
			commonMaterial1: 0,
			commonMaterial2: 0,
			commonMaterial3: 0,
			bossMaterial: 0,
			crown: 0,
		},
	},
	{
		level: 2,
		materials: {
			mora: 12500,
			bronzeTalentBooks: 3,
			silverTalentBooks: 0,
			goldTalentBooks: 0,
			commonMaterial1: 6,
			commonMaterial2: 0,
			commonMaterial3: 0,
			bossMaterial: 0,
			crown: 0,
		},
	},
	{
		level: 3,
		materials: {
			mora: 30000,
			bronzeTalentBooks: 3,
			silverTalentBooks: 2,
			goldTalentBooks: 0,
			commonMaterial1: 6,
			commonMaterial2: 3,
			commonMaterial3: 0,
			bossMaterial: 0,
			crown: 0,
		},
	},
	{
		level: 4,
		materials: {
			mora: 55000,
			bronzeTalentBooks: 3,
			silverTalentBooks: 6,
			goldTalentBooks: 0,
			commonMaterial1: 6,
			commonMaterial2: 7,
			commonMaterial3: 0,
			bossMaterial: 0,
			crown: 0,
		},
	},
	{
		level: 5,
		materials: {
			mora: 85000,
			bronzeTalentBooks: 3,
			silverTalentBooks: 12,
			goldTalentBooks: 0,
			commonMaterial1: 6,
			commonMaterial2: 13,
			commonMaterial3: 0,
			bossMaterial: 0,
			crown: 0,
		},
	},
	{
		level: 6,
		materials: {
			mora: 122500,
			bronzeTalentBooks: 3,
			silverTalentBooks: 21,
			goldTalentBooks: 0,
			commonMaterial1: 6,
			commonMaterial2: 22,
			commonMaterial3: 0,
			bossMaterial: 0,
			crown: 0,
		},
	},
	{
		level: 7,
		materials: {
			mora: 242500,
			bronzeTalentBooks: 3,
			silverTalentBooks: 21,
			goldTalentBooks: 4,
			commonMaterial1: 6,
			commonMaterial2: 22,
			commonMaterial3: 4,
			bossMaterial: 1,
			crown: 0,
		},
	},
	{
		level: 8,
		materials: {
			mora: 502500,
			bronzeTalentBooks: 3,
			silverTalentBooks: 21,
			goldTalentBooks: 10,
			commonMaterial1: 6,
			commonMaterial2: 22,
			commonMaterial3: 10,
			bossMaterial: 2,
			crown: 0,
		},
	},
	{
		level: 9,
		materials: {
			mora: 952500,
			bronzeTalentBooks: 3,
			silverTalentBooks: 21,
			goldTalentBooks: 22,
			commonMaterial1: 6,
			commonMaterial2: 22,
			commonMaterial3: 19,
			bossMaterial: 4,
			crown: 0,
		},
	},
	{
		level: 10,
		materials: {
			mora: 1652500,
			bronzeTalentBooks: 3,
			silverTalentBooks: 21,
			goldTalentBooks: 38,
			commonMaterial1: 6,
			commonMaterial2: 22,
			commonMaterial3: 31,
			bossMaterial: 6,
			crown: 1,
		},
	},
];
