import React from 'react';
import CardComponent from '../Layout/CardComponent';

const Domains = () => {
	return (
		<CardComponent title='Today in domains'>
			<div className=''>
				<div>
					<img
						width='96px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
					<img
						className='rounded-circle'
						width='80px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
					<img
						className='rounded-circle'
						width='80px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
					<img
						className='rounded-circle'
						width='80px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
					<img
						className='rounded-circle'
						width='80px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
				</div>
				<div>
					<img
						width='96px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
					<img
						className='rounded-circle'
						width='80px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
				</div>
				<div>
					<img
						width='96px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
					<img
						className='rounded-circle'
						width='80px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
				</div>
				<div>
					<img
						width='96px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
					<img
						className='rounded-circle'
						width='80px'
						src={
							'/images/Characters/mondstadt/Amber/images/Character_Amber_Thumb.png'
						}
						alt=''
					/>
				</div>
			</div>
		</CardComponent>
	);
};

export default Domains;
