import React from 'react';
import ConstellationsWrapper from '../../Constellations';
import Constellation from '../../Constellation';

const Constellations = props => {
	return (
		<ConstellationsWrapper>
			<Constellation
				level='1'
				image={props.constellation1Image}
				name={props.data.constellations[0].name}
				description="Transient Blossoms generated by Albedo's Abiogenesis: Solar Isotoma regenerate 1.2 Energy for Albedo.
								"
			/>
			<Constellation
				level='2'
				image={props.constellation2Image}
				name={props.data.constellations[1].name}
				description={
					<div>
						<div>
							Transient Blossoms generated by Abiogenesis: Solar Isotoma grant
							Albedo Fatal Reckoning for 30s:
						</div>
						<ul>
							<li>
								Unleashing Rite of Progeniture: Tectonic Tide consumes all
								stacks of Fatal Reckoning. Each stack of Fatal Reckoning
								consumed increases the DMG dealt by Fatal Blossoms and Rite of
								Progeniture: Tectonic Tide's burst DMG by 30% of Albedo's DEF.
							</li>
							<li>This effect stacks up to 4 times.</li>
						</ul>
					</div>
				}
			/>
			<Constellation
				level='3'
				image={props.constellation3Image}
				name={props.data.constellations[2].name}
				description={
					<div>
						<div>Increases the Level of Abiogenesis: Solar Isotoma by 3. .</div>
						<div>Maximum upgrade level is 15.</div>
					</div>
				}
			/>
			<Constellation
				level='4'
				image={props.constellation4Image}
				name={props.data.constellations[3].name}
				description='Active party members within the Solar Isotoma field have their Plunging Attack DMG increased by 30%.
								'
			/>
			<Constellation
				level='5'
				image={props.constellation5Image}
				name={props.data.constellations[4].name}
				description={
					<div>
						<div>
							Increases the Level of Rite of Progeniture: Tectonic Tide by 3.
						</div>
						<div>Maximum upgrade level is 15.</div>
					</div>
				}
			/>
			<Constellation
				level='6'
				image={props.constellation6Image}
				name={props.data.constellations[5].name}
				description='Active party members within the Solar Isotoma field who are protected by a shield created by Crystallize have their DMG increased by 17%.
								'
			/>
		</ConstellationsWrapper>
	);
};

export default Constellations;
