import React from 'react';
import CardComponent from '../../../Layout/CardComponent';

import AttributeScaling from '../../Talents/AttributeScaling';
import NormalAttack from '../../Talents/NormalAttack';
import ElementalSkill from '../../Talents/ElementalSkill';
import ElementalBurst from '../../Talents/ElementalBurst';
import PassiveTalent from '../../Talents/PassiveTalent';

const Talents = props => {
	let normalAttack = props.data.skillTalents[0].attributeScaling;
	let elementalSkill = props.data.skillTalents[1].attributeScaling;
	let elementalBurst = props.data.skillTalents[2].attributeScaling;
	return (
		<CardComponent title='Talents'>
			<NormalAttack
				name={props.data.skillTalents[0].name}
				image={props.normalAttackImage}
				normalAttack='Perform up to 5 rapid strikes.'
				chargedAttack='Consumes a certain amount of Stamina to unleash 2 rapid sword strikes.'
				plungingAttack='Plunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.'
			>
				<AttributeScaling data={normalAttack} />
			</NormalAttack>
			<ElementalSkill
				name={props.data.skillTalents[1].name}
				image={props.elementalSkillImage}
				description={
					<div>
						<b>Solar Isotoma</b>
						<div>has the following properties:</div>
						<ul>
							<li>
								When opponents within the Solar Isotoma field take DMG, the
								Solar Isotoma will generate Transient Blossoms which deal
								<b className='text-geo'> AoE Geo DMG</b>. DMG dealt scales off
								Albedo's DEF.
							</li>
							<li>Transient Blossoms can only be generated once every 2s.</li>
							<li>
								When a character is located at the locus of the Solar Isotoma,
								the Solar Isotoma will accumulate Geo power to form a
								crystallized platform that lifts the character up to a certain
								height. Only one crystallized platform can exist at a time.
							</li>
							<li>
								Solar Isotoma is considered a
								<b className='text-geo'> Geo Construct</b>. Only one Solar
								Isotoma created by Albedo himself can exist at any time.
							</li>
						</ul>
						<b>Hold</b> to designate the location of the skill.
					</div>
				}
			>
				<AttributeScaling data={elementalSkill} />
			</ElementalSkill>
			<ElementalBurst
				name={props.data.skillTalents[2].name}
				image={props.elementalBurstImage}
				description={
					<div>
						<div>
							Under Albedo's command, Geo crystals surge and burst forth,
							dealing
							<b className='text-geo'> AoE Geo DMG </b>
							in front of him.
						</div>
						<div>
							If a Solar Isotoma created by Albedo himself is on the field, 7
							Fatal Blossoms will be generated in the Solar Isotoma field,
							bursting violently into bloom and dealing
							<b className='text-geo'> AoE Geo DMG</b>.
						</div>
						<br />
						<div>
							Tecotonic Tide DMG and Fatal Blossom DMG will not generate
							Transient Blossoms.
						</div>
					</div>
				}
			>
				<AttributeScaling data={elementalBurst} />
			</ElementalBurst>
			<h3 className='text-start ms-3'>Passive Talents</h3>
			<PassiveTalent
				name={props.data.passiveTalents[0].name}
				image={props.passiveTalent1Image}
				unlocked='Unlocked at Ascension 1'
				description='Transient Blossoms generated by Abiogenesis: Solar Isotoma deal 25% more DMG to opponents whose HP is below 50%.'
			/>
			<PassiveTalent
				name={props.data.passiveTalents[1].name}
				image={props.passiveTalent2Image}
				unlocked='Unlocked at Ascension 4'
				description='Using Rite of Progeniture: Tectonic Tide increases the Elemental Mastery of nearby party members by 125 for 10s.
				'
			/>
			<PassiveTalent
				name={props.data.passiveTalents[2].name}
				image={props.passiveTalent3Image}
				unlocked='Unlocked Automatically'
				description='When Albedo crafts Weapon Ascension Materials, he has a 10% chance to receive double the product.
				'
			/>
		</CardComponent>
	);
};

export default Talents;
