import React from 'react';
import CardComponent from '../../../../Layout/CardComponent';
import Constellation from '../../../Constellation';

const Constellations = props => {
	return (
		<CardComponent title='Constellations'>
			<div className='mx-3 table-responsive'>
				<section>
					<table className='table table-dark table-sm align-middle'>
						<thead>
							<tr>
								<th scope='col'>Level</th>
								<th scope='col'>Icon</th>
								<th scope='col'>Name</th>
								<th scope='col'>Effect</th>
							</tr>
						</thead>
						<tbody>
							<Constellation
								level='1'
								image={props.constellation1Image}
								name={props.data.constellations[0].name}
								description='The number of Abundance Amulets that can be generated using Lightning Blade is increased to 3.'
							/>
							<Constellation
								level='2'
								image={props.constellation2Image}
								name={props.data.constellations[1].name}
								description={
									<div>
										When Falling Thunder created by Bellowing Thunder hits an
										opponent, it will decrease their Electro RES by 15% for 8s.
									</div>
								}
							/>
							<Constellation
								level='3'
								image={props.constellation3Image}
								name={props.data.constellations[2].name}
								description={
									<div>
										<div>Increases the Level of Bellowing Thunder by 3.</div>
										<div>Maximum upgrade level is 15.</div>
									</div>
								}
							/>
							<Constellation
								level='4'
								image={props.constellation4Image}
								name={props.data.constellations[3].name}
								description={
									<div>
										When a character obtains Abundance Amulets generated by
										Lightning Blade, if this character's Energy is less than
										35%, the Energy restored by the Abundance Amulets is
										increased by 100%.
									</div>
								}
							/>
							<Constellation
								level='5'
								image={props.constellation5Image}
								name={props.data.constellations[4].name}
								description={
									<div>
										<div>Increases the Level of Lightning Blade by 3.</div>
										<div>Maximum upgrade level is 15.</div>
									</div>
								}
							/>
							<Constellation
								level='6'
								image={props.constellation6Image}
								name={props.data.constellations[5].name}
								description={
									<div>
										Every 2 Falling Thunder attacks triggered by Bellowing
										Thunder will significantly increase the DMG dealt by the
										next Falling Thunder, dealing 200% of its original DMG, and
										will restore an additional 1 Energy to the current
										character.
									</div>
								}
							/>
							{props.children}
						</tbody>
					</table>
				</section>
			</div>
		</CardComponent>
	);
};

export default Constellations;
