import React from 'react';
import CardComponent from '../../../Layout/CardComponent';

import AttributeScaling from '../../Talents/AttributeScaling';
import NormalAttack from '../../Talents/NormalAttack';
import ElementalSkill from '../../Talents/ElementalSkill';
import ElementalBurst from '../../Talents/ElementalBurst';
import PassiveTalent from '../../Talents/PassiveTalent';

const Talents = props => {
	let normalAttack = props.data.skillTalents[0].attributeScaling;
	let elementalSkill = props.data.skillTalents[1].attributeScaling;
	let elementalBurst = props.data.skillTalents[2].attributeScaling;
	return (
		<CardComponent title='Talents'>
			<NormalAttack
				name={props.data.skillTalents[0].name}
				image={props.normalAttackImage}
				normalAttack={<div>Performs up to 5 consecutive spear strikes.</div>}
				chargedAttack={
					<div>
						Consumes a certain amount of Stamina to perform an upward slash.
					</div>
				}
				plungingAttack={
					<div>
						Plunges from mid-air to strike the ground below, damaging opponents
						along the path and dealing AoE DMG upon impact.
					</div>
				}
			>
				<AttributeScaling data={normalAttack} />
			</NormalAttack>
			<ElementalSkill
				name={props.data.skillTalents[1].name}
				image={props.elementalSkillImage}
				description={
					<div>
						<div>
							The Raiden Shogun unveils a shard of her Euthymia, dealing
							<b className='text-electro'> Electro DMG </b>
							to nearby opponents, and granting nearby party members the Eye of
							Stormy Judgment.
						</div>
						<br />
						<b>Eye of Stormy Judgment</b>
						<ul>
							<li>
								When characters with this buff attack and deal DMG to opponents,
								the Eye will unleash a coordinated attack, dealing
								<b className='text-electro'> AoE Electro DMG </b>
								at the opponent's position.
							</li>
							<li>
								Characters who gain the Eye of Stormy Judgment will have their
								Elemental Burst DMG increased based on the Energy Cost of the
								Elemental Burst during the Eye's duration.
							</li>
						</ul>
						<div>
							The Eye can initiate one coordinated attack every 0.9s per party.
						</div>
						<div>
							Coordinated attacks generated by characters not controlled by you
							deal 20% of the normal DMG.
						</div>
					</div>
				}
			>
				<AttributeScaling data={elementalSkill} />
			</ElementalSkill>
			<ElementalBurst
				name={props.data.skillTalents[2].name}
				image={props.elementalBurstImage}
				description={
					<div>
						<div>
							Gathering truths unnumbered and wishes uncounted, the Raiden
							Shogun unleashes the Musou no Hitotachi and deals
							<b className='text-electro'> AoE Electro DMG</b>, using Musou
							Isshin in combat for a certain duration afterward. The DMG dealt
							by Musou no Hitotachi and Musou Isshin's attacks will be increased
							based on the number of Chakra Desiderata's Resolve stacks consumed
							when this skill is used.
						</div>
						<br />
						<b>Musou Isshin</b>
						<div>
							While in this state, the Raiden Shogun will wield her tachi in
							battle, while her Normal, Charged, and Plunging Attacks will be
							infused with
							<b className='text-electro'> Electro DMG</b>, which cannot be
							overridden. When such attacks hit opponents, she will regenerate
							Energy for all nearby party members. Energy can be restored this
							way once every 1s, and this effect can be triggered 5 times
							throughout this skill's duration.
						</div>
						<div>
							While in this state, the Raiden Shogun's resistance to
							interruption is increased, and she is immune to
							<b className='text-electro'> Electro-Charged reaction DMG</b>.
						</div>
						<div>
							While Musou Isshin is active, the Raiden Shogun's Normal, Charged,
							and Plunging Attack DMG will be considered Elemental Burst DMG.
						</div>
						<br />
						<div>
							The effects of Musou Isshin will be cleared when the Raiden Shogun
							leaves the field.
						</div>
						<br />
						<b>Chakra Desiderata</b>
						<div>
							When nearby party members (excluding the Raiden Shogun herself)
							use their Elemental Bursts, the Raiden Shogun will build up
							Resolve stacks based on the Energy Cost of these Elemental Bursts.
						</div>
						<div>The maximum number of Resolve stacks is 60.</div>
						<br />
						<div>
							The Resolve gained by Chakra Desiderata will be cleared 300s after
							the Raiden Shogun leaves the field.
						</div>
					</div>
				}
			>
				<AttributeScaling data={elementalBurst} />
			</ElementalBurst>
			<h3 className='text-start ms-3'>Passive Talents</h3>
			<PassiveTalent
				name={props.data.passiveTalents[0].name}
				image={props.passiveTalent1Image}
				unlocked='Unlocked at Ascension 1'
				description={
					<div>
						<div>
							When nearby party members gain Elemental Orbs or Particles, Chakra
							Desiderata gains 2 Resolve stacks.
						</div>
						<div>This effect can occur once every 3s.</div>
					</div>
				}
			/>
			<PassiveTalent
				name={props.data.passiveTalents[1].name}
				image={props.passiveTalent2Image}
				unlocked='Unlocked at Ascension 4'
				description={
					<div>
						<div>
							Each 1% above 100% Energy Recharge that the Raiden Shogun
							possesses grants her:
						</div>
						<ul>
							<li>0.6% greater Energy restoration from Musou Isshin</li>
							<li>
								0.4%
								<b className='text-electro'> Electro DMG Bonus</b>
							</li>
						</ul>
					</div>
				}
			/>
			<PassiveTalent
				name={props.data.passiveTalents[2].name}
				image={props.passiveTalent3Image}
				unlocked='Unlocked Automatically'
				description={
					<div>
						Mora expended when ascending Swords and Polearms is decreased by
						50%.
					</div>
				}
			/>
		</CardComponent>
	);
};

export default Talents;
